force-app/main/default/objects/Framework__c/Framework__c.object-meta.xml
<CustomObject>
    <label>Framework</label>
    <nameField>
        <label>Framework Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Frameworks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Framework__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>Stores a link to the official Frameworks documentation site</description>
    <label>URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Regulyst Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Framework__c.field-meta.xml
<CustomField>
    <fullName>Framework__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Framework Template that will be plugged into the project which will determine the project requirements.</description>
    <label>Framework</label>
    <referenceTo>Framework__c</referenceTo>
    <relationshipName>Regulyst_Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Focus__c.field-meta.xml
<CustomField>
    <fullName>Project_Focus__c</fullName>
    <description>This defines the focus of the project. This will vary depending on the Standards Alignment Framework Body &amp; Framework chosen.</description>
    <label>Project Focus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Risk Management</fullName>
            </value>
            <value>
                <fullName>Audit Preperation</fullName>
            </value>
            <value>
                <fullName>Governance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Standards_Alignment_Body__c.field-meta.xml
<CustomField>
    <fullName>Standards_Alignment_Body__c</fullName>
    <label>Standards Alignment Body</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ISO</fullName>
            </value>
            <value>
                <fullName>DORA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Standards_Alignment_Framework__c.field-meta.xml
<CustomField>
    <fullName>Standards_Alignment_Framework__c</fullName>
    <description>Defines the Standard Alignment Framework as part of the project.</description>
    <label>Standards Alignment Framework</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Standards_Alignment_Body__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ISO 27001</fullName>
            </value>
            <value>
                <fullName>DORA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Framework__c/Project_Framework__c.object-meta.xml
<CustomObject>
    <label>Project Framework</label>
    <nameField>
        <label>Project Framework Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Frameworks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Framework__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Project Description, this is derived from the project framework chosen to run the project off</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project_Framework__c/fields/Framework__c.field-meta.xml
<CustomField>
    <fullName>Framework__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relates the project to the chosen framework</description>
    <label>Framework</label>
    <referenceTo>Framework__c</referenceTo>
    <relationshipLabel>Project Frameworks</relationshipLabel>
    <relationshipName>Project_Frameworks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Framework__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Relates to the Parent Object</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Frameworks</relationshipLabel>
    <relationshipName>Project_Frameworks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Framework__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>URL link to the Standards Body Organization</description>
    <label>URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project_Framework__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description>The version of the Framework the project is running off</description>
    <label>Version</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RecordDataController.cls
public with sharing class RecordDataController {
    @AuraEnabled(cacheable=true)
    public static Project__c getProjectWithFrameworks(Id projectId) {
        return [
            SELECT Id, Name, Description__c, Framework__c, Framework__r.Name, Project_Focus__c, Standards_Alignment_Body__c,Standards_Alignment_Framework__c,
                (SELECT Id, Name, Description__c, URL__c, Version__c FROM Project_Frameworks__r)
            FROM Project__c
            WHERE Id = :projectId
        ];
    }

    @AuraEnabled(cacheable=true)
    public static Project_Framework__c getProjectFramework(Id pfId) {
        return [
            SELECT Id, Name, Description__c, URL__c, Version__c, Framework__c, Project__c
            FROM Project_Framework__c
            WHERE Id = :pfId
        ];
    }
}