force-app/main/default/objects/Framework__c/Framework__c.object-meta.xml
<CustomObject>
    <label>Framework</label>
    <nameField>
        <label>Framework Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Frameworks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Regulyst Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Framework__c.field-meta.xml
<CustomField>
    <fullName>Framework__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Framework Template that will be plugged into the project which will determine the project requirements.</description>
    <label>Framework</label>
    <referenceTo>Framework__c</referenceTo>
    <relationshipName>Regulyst_Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Focus__c.field-meta.xml
<CustomField>
    <fullName>Project_Focus__c</fullName>
    <description>This defines the focus of the project. This will vary depending on the Standards Alignment Framework Body &amp; Framework chosen.</description>
    <label>Project Focus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Risk Management</fullName>
            </value>
            <value>
                <fullName>Audit Preperation</fullName>
            </value>
            <value>
                <fullName>Governance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Standards_Alignment_Framework__c.field-meta.xml
<CustomField>
    <fullName>Standards_Alignment_Framework__c</fullName>
    <description>Defines the Standard Alignment Framework as part of the project.</description>
    <label>Standards Alignment Framework</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Standards_Alignment_Body__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ISO 27001</fullName>
            </value>
            <value>
                <fullName>DORA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProjectTriggerService.cls
public with sharing class ProjectTriggerService {
    public static void setProjectname(List<SObject> newList){
        List<Id> projectIds = new List<Id>();
        for (SObject s : newList) {
            projectIds.add(s.Id);
        }
        List<Project__c> projects = [
            SELECT Id, Framework__r.Name, Project_Focus__c, Standards_Alignment_Framework__c
            FROM Project__c
            WHERE Id IN :projectIds
        ];
        List<Project__c> updateList = new List<Project__c>();
        for (Project__c proj : projects) {
            if (!String.isBlank(proj.Framework__r.Name) && !String.isBlank(proj.Project_Focus__c) && !String.isBlank(proj.Standards_Alignment_Framework__c) &&
                proj.Framework__r.Name.contains('ISO')) {
                proj.Name = 'Implementation of ISO for ' + proj.Project_Focus__c + ' under the ' +proj.Standards_Alignment_Framework__c + ' framework';
                updateList.add(proj);
            }
        }
        if (!updateList.isEmpty()) {
            update updateList;
        }
    }
}