force-app/main/default/objects/Evidence__c/Evidence__c.object-meta.xml
<CustomObject>
    <description>Object used to store proof of evidence against all types of project requirements</description>
    <label>Evidence</label>
    <nameField>
        <label>Evidence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evidences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evidence__c/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to indicate whether sufficient evidence is provided against the relevant requirement</description>
    <label>Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Evidence__c/fields/Project_Control__c.field-meta.xml
<CustomField>
    <fullName>Project_Control__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Enables users to link evidence directly to Controls</description>
    <label>Project Control</label>
    <referenceTo>Project_Control__c</referenceTo>
    <relationshipLabel>Evidences</relationshipLabel>
    <relationshipName>Evidences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evidence__c/fields/Project_Control_Requirement__c.field-meta.xml
<CustomField>
    <fullName>Project_Control_Requirement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Enables the user to link evidence to each low level control requirements</description>
    <label>Project Control Requirement</label>
    <referenceTo>Project_Control_Requirement__c</referenceTo>
    <relationshipLabel>Evidences</relationshipLabel>
    <relationshipName>Evidences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Framework__c/Framework__c.object-meta.xml
<CustomObject>
    <label>Framework</label>
    <nameField>
        <label>Framework Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Frameworks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Regulyst Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Framework__c.field-meta.xml
<CustomField>
    <fullName>Framework__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Framework Template that will be plugged into the project which will determine the project requirements.</description>
    <label>Framework</label>
    <referenceTo>Framework__c</referenceTo>
    <relationshipName>Regulyst_Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Standards_Alignment_Body__c.field-meta.xml
<CustomField>
    <fullName>Standards_Alignment_Body__c</fullName>
    <label>Standards Alignment Body</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ISO</fullName>
            </value>
            <value>
                <fullName>DORA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Standards_Alignment_Framework__c.field-meta.xml
<CustomField>
    <fullName>Standards_Alignment_Framework__c</fullName>
    <description>Defines the Standard Alignment Framework as part of the project.</description>
    <label>Standards Alignment Framework</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Standards_Alignment_Body__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ISO 27001</fullName>
            </value>
            <value>
                <fullName>DORA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Analytics__c/Project_Analytics__c.object-meta.xml
<CustomObject>
    <description>Object used to store important data analytics and KPI&apos;s for Projects</description>
    <label>Project Analytics</label>
    <nameField>
        <label>Project Analytics Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Analytics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Analytics__c/fields/Approved_Control_Requirements__c.field-meta.xml
<CustomField>
    <fullName>Approved_Control_Requirements__c</fullName>
    <label>Approved Control Requirements</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Analytics__c/fields/Control_Requirements_With_Evidence__c.field-meta.xml
<CustomField>
    <fullName>Control_Requirements_With_Evidence__c</fullName>
    <label>Control Requirements With Evidence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Analytics__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Field to relate this to it&apos;s parent Project Record</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Analytics</relationshipLabel>
    <relationshipName>Project_Analytics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Analytics__c/fields/Total_Clauses__c.field-meta.xml
<CustomField>
    <fullName>Total_Clauses__c</fullName>
    <label>Total Clauses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Analytics__c/fields/Total_Control_Requirements__c.field-meta.xml
<CustomField>
    <fullName>Total_Control_Requirements__c</fullName>
    <label>Total Control Requirements</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Analytics__c/fields/Total_Controls__c.field-meta.xml
<CustomField>
    <fullName>Total_Controls__c</fullName>
    <label>Total Controls</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Analytics__c/fields/Total_Evidence_Collected__c.field-meta.xml
<CustomField>
    <fullName>Total_Evidence_Collected__c</fullName>
    <description>Percentage of total evidence collected against requirements</description>
    <label>Total Evidence Collected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Project_Clause_Control_Domain__c/Project_Clause_Control_Domain__c.object-meta.xml
<CustomObject>
    <label>Clause/Control Domain</label>
    <nameField>
        <label>Clause/Control Domain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clause/Control Domain</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Clause_Control_Domain__c/fields/Project_Framework__c.field-meta.xml
<CustomField>
    <fullName>Project_Framework__c</fullName>
    <description>Parent Project Framework above the clause</description>
    <label>Framework</label>
    <referenceTo>Project_Framework__c</referenceTo>
    <relationshipName>Clause_Control_Domain</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Control__c/Project_Control__c.object-meta.xml
<CustomObject>
    <description>Specific Controls in place inherited from the Project framework chosen. Controls represent specific lower level aspects of the project Framework and Clauses</description>
    <label>Control</label>
    <nameField>
        <label>Control Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Control__c/fields/Project_Framework__c.field-meta.xml
<CustomField>
    <fullName>Project_Framework__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relates to the Parent top level Framework</description>
    <label>Project Framework</label>
    <referenceTo>Project_Framework__c</referenceTo>
    <relationshipLabel>Project Controls</relationshipLabel>
    <relationshipName>Project_Controls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Control_Requirement__c/Project_Control_Requirement__c.object-meta.xml
<CustomObject>
    <label>Project Control Requirement</label>
    <nameField>
        <label>Project Control Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Control Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Control_Requirement__c/fields/Framework__c.field-meta.xml
<CustomField>
    <fullName>Framework__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship to top level Project Framework</description>
    <label>Framework</label>
    <referenceTo>Project_Framework__c</referenceTo>
    <relationshipLabel>Project Control Requirements</relationshipLabel>
    <relationshipName>Project_Control_Requirements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Control_Requirement__c/fields/Project_Control__c.field-meta.xml
<CustomField>
    <fullName>Project_Control__c</fullName>
    <description>Relationship to Parent Project Control</description>
    <label>Project Control</label>
    <referenceTo>Project_Control__c</referenceTo>
    <relationshipLabel>Project Control Requirements</relationshipLabel>
    <relationshipName>Project_Control_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Framework__c/Project_Framework__c.object-meta.xml
<CustomObject>
    <label>Project Framework</label>
    <nameField>
        <label>Project Framework Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Frameworks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Framework__c/fields/Framework__c.field-meta.xml
<CustomField>
    <fullName>Framework__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relates the project to the chosen framework</description>
    <label>Framework</label>
    <referenceTo>Framework__c</referenceTo>
    <relationshipLabel>Project Frameworks</relationshipLabel>
    <relationshipName>Project_Frameworks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Framework__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Relates to the Parent Object</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Frameworks</relationshipLabel>
    <relationshipName>Project_Frameworks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProjectAnalyticsController.cls
public with sharing class ProjectAnalyticsController {
    @AuraEnabled(cacheable=true)
    public static Project_Analytics__c getAnalytics(Id projectId) {
        Project__c project = [
            SELECT Id, Standards_Alignment_Body__c, Standards_Alignment_Framework__c 
            FROM Project__c 
            WHERE Id = :projectId 
            LIMIT 1
        ];

        if (project.Standards_Alignment_Body__c != 'ISO' || 
            project.Standards_Alignment_Framework__c != 'ISO 27001') {
            return null;
        }

        Id projectFrameworkId = [
            SELECT Id 
            FROM Project_Framework__c 
            WHERE Project__c = :projectId 
            LIMIT 1
        ].Id;

        Integer totalClauses = [
            SELECT COUNT() 
            FROM Project_Clause_Control_Domain__c 
            WHERE Project_Framework__c = :projectFrameworkId
        ];

        Integer totalControls = [
            SELECT COUNT() 
            FROM Project_Control__c 
            WHERE Project_Framework__c = :projectFrameworkId
        ];

        Integer totalRequirements = [
            SELECT COUNT() 
            FROM Project_Control_Requirement__c 
            WHERE Framework__c = :projectFrameworkId
        ];

        Integer withEvidence = [
            SELECT COUNT() 
            FROM Evidence__c 
            WHERE Project_Control_Requirement__c != null
        ];

        Integer approved = [
            SELECT COUNT() 
            FROM Evidence__c 
            WHERE Project_Control_Requirement__c != null AND Approved__c = TRUE
        ];

        Project_Analytics__c analytics = new Project_Analytics__c(
            Total_Clauses__c = totalClauses,
            Total_Controls__c = totalControls,
            Total_Control_Requirements__c = totalRequirements,
            Control_Requirements_With_Evidence__c = withEvidence,
            Approved_Control_Requirements__c = approved,
            Project__c = projectId,
            Last_Updated__c = System.now(),
            Total_Evidence_Collected__c = withEvidence/totalRequirements
        );

        return analytics;
    }
}